- 
  name: Install & Configure MariaDB
  hosts: target2
  tasks:
    - name: Install Mariadb dependency
      yum:
        name: MySQL-python
        state: present
    
    - name: Install Mariadb-Server Package
      yum:
        name: mariadb-server
        state: present
    
    - name: Start Mariadb Service
      service:
        name: mariadb
        enabled: true
        state: started
    
    - firewalld:
        port: 3306/tcp
        zone: public
        permanent: yes
        state: enabled
    
    - service:
        name: firewalld
        state: reloaded
    
    - name: Create a new DB
      mysql_db:
        name: ecomdb
        state: present

    - name: Create DB User
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: '*.*:ALL'
        state: present

    - name: Run a script
      script: /home/tux/ansible-local-repo/ansible-demos-exercises/Final-Project/Flush-Priv.sh

    - name: Copy Sql Script File to /tmp Dir
      copy:
        src: /home/tux/ansible-local-repo/ansible-demos-exercises/Final-Project/db-load-script.sql
        dest: /tmp/db-load-script.sql
    
    - name: Run Bash Script to insert data to the table
      script: /home/tux/ansible-local-repo/ansible-demos-exercises/Final-Project/MySql-Script.sh
