-
  name: DB Installation & Configuration on target1 Node
  hosts: target1
  vars:
    packages:
     - firewalld
     - MySQL-python
     - mariadb-server

  tasks:
    - name: DB & Firewall Installation
      yum:
        name: '{{ packages }}'
        state: present

    - name: Start firewall service
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Start mariadb service
      service:
        name: mariadb
        enabled: true
        state: started
        
    - name: Adjust Firewall Configuration
      firewalld:
        port: 3306/tcp
        zone: public
        permanent: yes
        state: enabled
        
    - name: Reload Firewall Configuration
      service:
        name: firewalld
        state: reloaded
    -
      name: Copy Root Password for DB
      copy:
        src: /home/tux/ansible-local-repo/ansible-demos-exercises/Final-Project/my.cnf
        dest: /root/.my.cnf
      
    - name: Create a new mariaDB
      mysql_db:
        name: ecomdb
        state: present

    - name: Create new mariaDB user
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: '*.*:ALL'
        state: present

    - name: Run script to Grant & flush privileges to the created user.
      script: /home/tux/ansible-local-repo/ansible-demos-exercises/Final-Project/Flush-Priv.sh

    - name: Copy Sql Script File to /tmp Dir
      copy:
        src: /home/tux/ansible-local-repo/ansible-demos-exercises/Final-Project/db-load-script.sql
        dest: /tmp/db-load-script.sql

    - name: Run SQL Script to insert data to the table
      script: /home/tux/ansible-local-repo/ansible-demos-exercises/Final-Project/MySql-Script.sh

-
    name: Web Service Installation and Configuration on target2 Node
    hosts: target2
    vars:
      packages:
        - httpd
        - php
        - php-mysql
        - git
    tasks:
    - name: WS & Firewall Installation
      yum:
        name: '{{ packages }}'
        state: present

    - name: Start firewall service
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Adjust Firewall Configuration
      firewalld:
        port: 80/tcp
        zone: public
        permanent: yes
        state: enabled

    - name: Reload Firewall Configuration
      service:
        name: firewalld
        state: reloaded

    - name: Start httpd service
      service:
        name: httpd
        enabled: true
        state: started

    - name: Clone a repo
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        force: yes

    - name: Modify httpd configuration file
      command: sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf

    - name: Configure index.php file
      command: sed -i 's/localhost/192.168.1.28/g' /var/www/html/index.php

    - name: Restart httpd
      service:
        name: httpd
        state: restarted
