# remain flush privilages and run the sql script
# also the http
- 
  name: Install & Configure MariaDB
  hosts: target2
  tasks:
    - name: Install dependencies
      yum:
        name: MySQL-python
        state: present
    
    - name: Install The Package
      yum:
        name: mariadb-server
        state: present
    
    - name: Start The Service
      service:
        name: mariadb
        enabled: true
        state: started
    
    - firewalld:
        port: 3306/tcp
        zone: public
        permanent: yes
        state: enabled
    
    - service:
        name: firewalld
        state: reloaded

    - name: Create a new DB
      mysql_db:
        name: ecomdb
        state: present

    - name: Create DB User
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: '*.*:ALL'
        state: present
